
package vn.com.fpt.authServ;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthenticationService", targetNamespace = "http://interfaces.fpt.com.vn/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface AuthenticationService {

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	@Action(input = "http://interfaces.fpt.com.vn/AuthenticationService/getAuthenticationRequest", output = "http://interfaces.fpt.com.vn/AuthenticationService/getAuthenticationResponse")
	public String getAuthentication();

}
